source 'https://github.com/CocoaPods/Specs.git'

target 'UCTransitWidgets', :exclusive => true do
  pod "UCTransitWidgets", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UCTransitWidgets", :path => "../"

  pod 'Expecta', '~> 1.0.2'
  pod 'FBSnapshotTestCase', '1.8'
  pod 'Specta', '~> 1.0.2'
  pod 'Expecta+Snapshots', '1.3.4'
end
