language: objective-c

before_install:
- gem install cocoapods
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/UCTransitWidgets.xcworkspace -scheme UCTransitWidgets-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
notifications:
  email: false
