//
//  UCWMTABusIconView.m
//  Pods
//
//  Created by James Paolantonio on 1/26/15.
//
//

#import "UCWMTABusIconView.h"

#import "UCTransitLine.h"
#import "UIColor+UCTransitColor.h"

@interface UCWMTABusIconView ()
@property (nonatomic) NSString *displayName;
@end

@implementation UCWMTABusIconView

- (instancetype)initWithLine:(UCTransitLine *)line {
    self = [super initWithLine:line];
    if (self) {
        self.displayName = [self displayNameForLine:line.lineCode];
    }
    return self;
}

- (void)setBounds:(CGRect)bounds {
    CGSize origSize = self.bounds.size;
    [super setBounds:bounds];
    if (!CGSizeEqualToSize(bounds.size, origSize)) {
        [self setNeedsDisplay];
    }
}

- (void)setFrame:(CGRect)frame {
    CGSize origSize = self.frame.size;
    [super setFrame:frame];
    if (!CGSizeEqualToSize(frame.size, origSize)) {
        [self setNeedsDisplay];
    }
}

- (void)drawRect:(CGRect)rect {
    UIColor *foreColor = [self displayColorForLine:self.line.lineCode];

    CGFloat widthHeight = MIN(self.bounds.size.width, self.bounds.size.height);

    CGFloat heightPct = 0.65f;
    if (widthHeight <= 20.f) {
        heightPct = 0.8f;
    } else if (widthHeight <= 40.f) {
        heightPct = 0.7f;
    }
    CGFloat baseSize = 10.f;
    UIFont *testFont = [UIFont fontWithName:@"Helvetica-Bold" size:baseSize];
    CGFloat testHeight = [self.displayName sizeWithAttributes:@{ NSFontAttributeName: testFont }].height;

    CGFloat multiplier = (heightPct * widthHeight) / testHeight;
    UIFont *font = [UIFont fontWithName:@"Helvetica-Bold" size:multiplier * baseSize];
    CGSize textSize = [self.displayName sizeWithAttributes:@{ NSFontAttributeName: font }];
    CGPoint p = CGPointMake(self.bounds.size.width / 2.f - textSize.width / 2.f,
                            self.bounds.size.height / 2.f - textSize.height / 2.f);
    [self.displayName drawAtPoint:p withAttributes:@{ NSFontAttributeName: font,
                                                      NSForegroundColorAttributeName: foreColor}];
}

- (UIColor *)displayColorForLine:(UCTransitLineWMTABus)line {
    switch (line) {
        case UCWMTA5A: return [UIColor colorWithHex:0x000000]; break;
        case UCWMTA16X: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTA16Y: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTA28X: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTA37: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTA79: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTAA9: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTAK9: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTAS9: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTAX9: return [UIColor colorWithHex:0x004d7d]; break;
        case UCWMTA1C: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA22A: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA22B: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA25A: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA25B: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA25C: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA25D: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA25E: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA26A: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA29K: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA29N: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA2T: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA3A: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA3T: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA4A: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA4B: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA60: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA62: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA63: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA64: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA74: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA89: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA89M: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA94: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA96: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA97: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA9A: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAA4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAB21: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAB22: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAB24: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAB25: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAB8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAB9: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAC12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAC14: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAC21: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAC22: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAC26: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAC29: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD13: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD14: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAD8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAE6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF1: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF13: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF14: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAF8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAG12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAG13: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAG14: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAG16: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAG2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAG8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAH11: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAH12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAH13: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAH6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAH8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAH9: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAJ11: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAJ12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAJ13: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAJ4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAK11: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAL1: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAL2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAL8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAM4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAM6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAN2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAN3: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAN4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAN6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTANH1: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTANH3: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAP6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAR1: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAR11: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAR12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAR2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAR4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAS80: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAS91: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAT2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAU2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAU4: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAU5: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAU6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAV12: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAV14: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAV15: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAV7: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAV8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAV9: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAW2: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAW3: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAW5: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAW6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAW8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAX8: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTAZ6: return [UIColor colorWithHex:0x0088b2]; break;
        case UCWMTA11Y: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA15K: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA15L: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA15M: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA16L: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17A: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17B: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17F: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17G: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17H: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17K: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17L: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA17M: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18E: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18F: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18G: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18H: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18J: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18P: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18R: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA18S: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA21A: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA21D: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA28F: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA28G: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA29C: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA29E: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA29G: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA29H: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA29X: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA3Y: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA87: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA8S: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA8W: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA8Z: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAA31: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAA32: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAA33: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAB27: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAB29: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAB31: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAB51: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAC11: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAC13: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAC28: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAC40: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD1: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD3: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD31: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD32: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD33: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD34: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD5: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAD51: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAE32: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAH1: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAJ5: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAJ7: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAJ9: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAK2: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAM31: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAP17: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAP18: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAP19: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAR3: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAS1: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAS35: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAS41: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAV5: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAW13: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAW14: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAW15: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAW19: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAW45: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAW47: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAX1: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAX3: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAZ11: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAZ13: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAZ2: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAZ29: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTAZ9: return [UIColor colorWithHex:0x687274]; break;
        case UCWMTA10R: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA10S: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA13Y: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA30N: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA30S: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA33: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA34: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA39: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA90: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA92: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAB30: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAC27: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAK12: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAK13: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAMWY: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAT14: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAW1: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAW9: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTAY2: return [UIColor colorWithHex:0xaaaaaa]; break;
        case UCWMTA10A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA10B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA10E: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16D: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16E: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16G: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16H: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16J: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16K: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA16P: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA1A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA1B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA1E: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA1Z: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA23A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA23B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA23T: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA28A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA2A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA2B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA31: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA32: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA36: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA38B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA42: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA43: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA52: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA53: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA54: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA70: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7A: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7B: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7C: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7F: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7H: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7M: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7P: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7W: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7X: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA7Y: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA80: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA81: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA82: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA83: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA86: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTA93: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA11: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA12: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA42: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA46: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA48: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA6: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA7: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAA8: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAB2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAC2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAC4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAC8: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAE2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAE3: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAE4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAF4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAH2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAH3: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAH4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAJ1: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAJ2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAJ3: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAK6: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAP12: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAQ1: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAQ2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAQ4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAQ5: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAQ6: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAREX: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAS2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAS4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAT18: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAU8: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAW4: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAX2: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAY7: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAY8: return [UIColor colorWithHex:0xc53c31]; break;
        case UCWMTAZ8: return [UIColor colorWithHex:0xc53c31]; break;
    }
}

- (NSString *)displayNameForLine:(UCTransitLineWMTABus)line {
    switch (line) {
        case UCWMTA10A: return  @"10A"; break;
        case UCWMTA10B: return  @"10B"; break;
        case UCWMTA10E: return  @"10E"; break;
        case UCWMTA10R: return  @"10R"; break;
        case UCWMTA10S: return  @"10S"; break;
        case UCWMTA11Y: return  @"11Y"; break;
        case UCWMTA13Y: return  @"13Y"; break;
        case UCWMTA15K: return  @"15K"; break;
        case UCWMTA15L: return  @"15L"; break;
        case UCWMTA15M: return  @"15M"; break;
        case UCWMTA16A: return  @"16A"; break;
        case UCWMTA16B: return  @"16B"; break;
        case UCWMTA16D: return  @"16D"; break;
        case UCWMTA16E: return  @"16E"; break;
        case UCWMTA16G: return  @"16G"; break;
        case UCWMTA16H: return  @"16H"; break;
        case UCWMTA16J: return  @"16J"; break;
        case UCWMTA16K: return  @"16K"; break;
        case UCWMTA16L: return  @"16L"; break;
        case UCWMTA16P: return  @"16P"; break;
        case UCWMTA16X: return  @"16X"; break;
        case UCWMTA16Y: return  @"16Y"; break;
        case UCWMTA17A: return  @"17A"; break;
        case UCWMTA17B: return  @"17B"; break;
        case UCWMTA17F: return  @"17F"; break;
        case UCWMTA17G: return  @"17G"; break;
        case UCWMTA17H: return  @"17H"; break;
        case UCWMTA17K: return  @"17K"; break;
        case UCWMTA17L: return  @"17L"; break;
        case UCWMTA17M: return  @"17M"; break;
        case UCWMTA18E: return  @"18E"; break;
        case UCWMTA18F: return  @"18F"; break;
        case UCWMTA18G: return  @"18G"; break;
        case UCWMTA18H: return  @"18H"; break;
        case UCWMTA18J: return  @"18J"; break;
        case UCWMTA18P: return  @"18P"; break;
        case UCWMTA18R: return  @"18R"; break;
        case UCWMTA18S: return  @"18S"; break;
        case UCWMTA1A: return  @"1A"; break;
        case UCWMTA1B: return  @"1B"; break;
        case UCWMTA1C: return  @"1C"; break;
        case UCWMTA1E: return  @"1E"; break;
        case UCWMTA1Z: return  @"1Z"; break;
        case UCWMTA21A: return  @"21A"; break;
        case UCWMTA21D: return  @"21D"; break;
        case UCWMTA22A: return  @"22A"; break;
        case UCWMTA22B: return  @"22B"; break;
        case UCWMTA23A: return  @"23A"; break;
        case UCWMTA23B: return  @"23B"; break;
        case UCWMTA23T: return  @"23T"; break;
        case UCWMTA25A: return  @"25A"; break;
        case UCWMTA25B: return  @"25B"; break;
        case UCWMTA25C: return  @"25C"; break;
        case UCWMTA25D: return  @"25D"; break;
        case UCWMTA25E: return  @"25E"; break;
        case UCWMTA26A: return  @"26A"; break;
        case UCWMTA28A: return  @"28A"; break;
        case UCWMTA28F: return  @"28F"; break;
        case UCWMTA28G: return  @"28G"; break;
        case UCWMTA28X: return  @"28X"; break;
        case UCWMTA29C: return  @"29C"; break;
        case UCWMTA29E: return  @"29E"; break;
        case UCWMTA29G: return  @"29G"; break;
        case UCWMTA29H: return  @"29H"; break;
        case UCWMTA29K: return  @"29K"; break;
        case UCWMTA29N: return  @"29N"; break;
        case UCWMTA29X: return  @"29X"; break;
        case UCWMTA2A: return  @"2A"; break;
        case UCWMTA2B: return  @"2B"; break;
        case UCWMTA2T: return  @"2T"; break;
        case UCWMTA30N: return  @"30N"; break;
        case UCWMTA30S: return  @"30S"; break;
        case UCWMTA31: return  @"31"; break;
        case UCWMTA32: return  @"32"; break;
        case UCWMTA33: return  @"33"; break;
        case UCWMTA34: return  @"34"; break;
        case UCWMTA36: return  @"36"; break;
        case UCWMTA37: return  @"37"; break;
        case UCWMTA38B: return  @"38B"; break;
        case UCWMTA39: return  @"39"; break;
        case UCWMTA3A: return  @"3A"; break;
        case UCWMTA3T: return  @"3T"; break;
        case UCWMTA3Y: return  @"3Y"; break;
        case UCWMTA42: return  @"42"; break;
        case UCWMTA43: return  @"43"; break;
        case UCWMTA4A: return  @"4A"; break;
        case UCWMTA4B: return  @"4B"; break;
        case UCWMTA52: return  @"52"; break;
        case UCWMTA53: return  @"53"; break;
        case UCWMTA54: return  @"54"; break;
        case UCWMTA5A: return  @"5A"; break;
        case UCWMTA60: return  @"60"; break;
        case UCWMTA62: return  @"62"; break;
        case UCWMTA63: return  @"63"; break;
        case UCWMTA64: return  @"64"; break;
        case UCWMTA70: return  @"70"; break;
        case UCWMTA74: return  @"74"; break;
        case UCWMTA79: return  @"79"; break;
        case UCWMTA7A: return  @"7A"; break;
        case UCWMTA7B: return  @"7B"; break;
        case UCWMTA7C: return  @"7C"; break;
        case UCWMTA7F: return  @"7F"; break;
        case UCWMTA7H: return  @"7H"; break;
        case UCWMTA7M: return  @"7M"; break;
        case UCWMTA7P: return  @"7P"; break;
        case UCWMTA7W: return  @"7W"; break;
        case UCWMTA7X: return  @"7X"; break;
        case UCWMTA7Y: return  @"7Y"; break;
        case UCWMTA80: return  @"80"; break;
        case UCWMTA81: return  @"81"; break;
        case UCWMTA82: return  @"82"; break;
        case UCWMTA83: return  @"83"; break;
        case UCWMTA86: return  @"86"; break;
        case UCWMTA87: return  @"87"; break;
        case UCWMTA89: return  @"89"; break;
        case UCWMTA89M: return  @"89M"; break;
        case UCWMTA8S: return  @"8S"; break;
        case UCWMTA8W: return  @"8W"; break;
        case UCWMTA8Z: return  @"8Z"; break;
        case UCWMTA90: return  @"90"; break;
        case UCWMTA92: return  @"92"; break;
        case UCWMTA93: return  @"93"; break;
        case UCWMTA94: return  @"94"; break;
        case UCWMTA96: return  @"96"; break;
        case UCWMTA97: return  @"97"; break;
        case UCWMTA9A: return  @"9A"; break;
        case UCWMTAA11: return  @"A11"; break;
        case UCWMTAA12: return  @"A12"; break;
        case UCWMTAA2: return  @"A2"; break;
        case UCWMTAA31: return  @"A31"; break;
        case UCWMTAA32: return  @"A32"; break;
        case UCWMTAA33: return  @"A33"; break;
        case UCWMTAA4: return  @"A4"; break;
        case UCWMTAA42: return  @"A42"; break;
        case UCWMTAA46: return  @"A46"; break;
        case UCWMTAA48: return  @"A48"; break;
        case UCWMTAA6: return  @"A6"; break;
        case UCWMTAA7: return  @"A7"; break;
        case UCWMTAA8: return  @"A8"; break;
        case UCWMTAA9: return  @"A9"; break;
        case UCWMTAB2: return  @"B2"; break;
        case UCWMTAB21: return  @"B21"; break;
        case UCWMTAB22: return  @"B22"; break;
        case UCWMTAB24: return  @"B24"; break;
        case UCWMTAB25: return  @"B25"; break;
        case UCWMTAB27: return  @"B27"; break;
        case UCWMTAB29: return  @"B29"; break;
        case UCWMTAB30: return  @"B30"; break;
        case UCWMTAB31: return  @"B31"; break;
        case UCWMTAB51: return  @"B51"; break;
        case UCWMTAB8: return  @"B8"; break;
        case UCWMTAB9: return  @"B9"; break;
        case UCWMTAC11: return  @"C11"; break;
        case UCWMTAC12: return  @"C12"; break;
        case UCWMTAC13: return  @"C13"; break;
        case UCWMTAC14: return  @"C14"; break;
        case UCWMTAC2: return  @"C2"; break;
        case UCWMTAC21: return  @"C21"; break;
        case UCWMTAC22: return  @"C22"; break;
        case UCWMTAC26: return  @"C26"; break;
        case UCWMTAC27: return  @"C27"; break;
        case UCWMTAC28: return  @"C28"; break;
        case UCWMTAC29: return  @"C29"; break;
        case UCWMTAC4: return  @"C4"; break;
        case UCWMTAC40: return  @"C40"; break;
        case UCWMTAC8: return  @"C8"; break;
        case UCWMTAD1: return  @"D1"; break;
        case UCWMTAD12: return  @"D12"; break;
        case UCWMTAD13: return  @"D13"; break;
        case UCWMTAD14: return  @"D14"; break;
        case UCWMTAD2: return  @"D2"; break;
        case UCWMTAD3: return  @"D3"; break;
        case UCWMTAD31: return  @"D31"; break;
        case UCWMTAD32: return  @"D32"; break;
        case UCWMTAD33: return  @"D33"; break;
        case UCWMTAD34: return  @"D34"; break;
        case UCWMTAD4: return  @"D4"; break;
        case UCWMTAD5: return  @"D5"; break;
        case UCWMTAD51: return  @"D51"; break;
        case UCWMTAD6: return  @"D6"; break;
        case UCWMTAD8: return  @"D8"; break;
        case UCWMTAE2: return  @"E2"; break;
        case UCWMTAE3: return  @"E3"; break;
        case UCWMTAE32: return  @"E32"; break;
        case UCWMTAE4: return  @"E4"; break;
        case UCWMTAE6: return  @"E6"; break;
        case UCWMTAF1: return  @"F1"; break;
        case UCWMTAF12: return  @"F12"; break;
        case UCWMTAF13: return  @"F13"; break;
        case UCWMTAF14: return  @"F14"; break;
        case UCWMTAF2: return  @"F2"; break;
        case UCWMTAF4: return  @"F4"; break;
        case UCWMTAF6: return  @"F6"; break;
        case UCWMTAF8: return  @"F8"; break;
        case UCWMTAG12: return  @"G12"; break;
        case UCWMTAG13: return  @"G13"; break;
        case UCWMTAG14: return  @"G14"; break;
        case UCWMTAG16: return  @"G16"; break;
        case UCWMTAG2: return  @"G2"; break;
        case UCWMTAG8: return  @"G8"; break;
        case UCWMTAH1: return  @"H1"; break;
        case UCWMTAH11: return  @"H11"; break;
        case UCWMTAH12: return  @"H12"; break;
        case UCWMTAH13: return  @"H13"; break;
        case UCWMTAH2: return  @"H2"; break;
        case UCWMTAH3: return  @"H3"; break;
        case UCWMTAH4: return  @"H4"; break;
        case UCWMTAH6: return  @"H6"; break;
        case UCWMTAH8: return  @"H8"; break;
        case UCWMTAH9: return  @"H9"; break;
        case UCWMTAJ1: return  @"J1"; break;
        case UCWMTAJ11: return  @"J11"; break;
        case UCWMTAJ12: return  @"J12"; break;
        case UCWMTAJ13: return  @"J13"; break;
        case UCWMTAJ2: return  @"J2"; break;
        case UCWMTAJ3: return  @"J3"; break;
        case UCWMTAJ4: return  @"J4"; break;
        case UCWMTAJ5: return  @"J5"; break;
        case UCWMTAJ7: return  @"J7"; break;
        case UCWMTAJ9: return  @"J9"; break;
        case UCWMTAK11: return  @"K11"; break;
        case UCWMTAK12: return  @"K12"; break;
        case UCWMTAK13: return  @"K13"; break;
        case UCWMTAK2: return  @"K2"; break;
        case UCWMTAK6: return  @"K6"; break;
        case UCWMTAK9: return  @"K9"; break;
        case UCWMTAL1: return  @"L1"; break;
        case UCWMTAL2: return  @"L2"; break;
        case UCWMTAL8: return  @"L8"; break;
        case UCWMTAM31: return  @"M31"; break;
        case UCWMTAM4: return  @"M4"; break;
        case UCWMTAM6: return  @"M6"; break;
        case UCWMTAMWY: return  @"MWY"; break;
        case UCWMTAN2: return  @"N2"; break;
        case UCWMTAN3: return  @"N3"; break;
        case UCWMTAN4: return  @"N4"; break;
        case UCWMTAN6: return  @"N6"; break;
        case UCWMTANH1: return  @"NH1"; break;
        case UCWMTANH3: return  @"NH3"; break;
        case UCWMTAP12: return  @"P12"; break;
        case UCWMTAP17: return  @"P17"; break;
        case UCWMTAP18: return  @"P18"; break;
        case UCWMTAP19: return  @"P19"; break;
        case UCWMTAP6: return  @"P6"; break;
        case UCWMTAQ1: return  @"Q1"; break;
        case UCWMTAQ2: return  @"Q2"; break;
        case UCWMTAQ4: return  @"Q4"; break;
        case UCWMTAQ5: return  @"Q5"; break;
        case UCWMTAQ6: return  @"Q6"; break;
        case UCWMTAR1: return  @"R1"; break;
        case UCWMTAR11: return  @"R11"; break;
        case UCWMTAR12: return  @"R12"; break;
        case UCWMTAR2: return  @"R2"; break;
        case UCWMTAR3: return  @"R3"; break;
        case UCWMTAR4: return  @"R4"; break;
        case UCWMTAREX: return  @"REX"; break;
        case UCWMTAS1: return  @"S1"; break;
        case UCWMTAS2: return  @"S2"; break;
        case UCWMTAS35: return  @"S35"; break;
        case UCWMTAS4: return  @"S4"; break;
        case UCWMTAS41: return  @"S41"; break;
        case UCWMTAS80: return  @"S80"; break;
        case UCWMTAS9: return  @"S9"; break;
        case UCWMTAS91: return  @"S91"; break;
        case UCWMTAT14: return  @"T14"; break;
        case UCWMTAT18: return  @"T18"; break;
        case UCWMTAT2: return  @"T2"; break;
        case UCWMTAU2: return  @"U2"; break;
        case UCWMTAU4: return  @"U4"; break;
        case UCWMTAU5: return  @"U5"; break;
        case UCWMTAU6: return  @"U6"; break;
        case UCWMTAU8: return  @"U8"; break;
        case UCWMTAV12: return  @"V12"; break;
        case UCWMTAV14: return  @"V14"; break;
        case UCWMTAV15: return  @"V15"; break;
        case UCWMTAV5: return  @"V5"; break;
        case UCWMTAV7: return  @"V7"; break;
        case UCWMTAV8: return  @"V8"; break;
        case UCWMTAV9: return  @"V9"; break;
        case UCWMTAW1: return  @"W1"; break;
        case UCWMTAW13: return  @"W13"; break;
        case UCWMTAW14: return  @"W14"; break;
        case UCWMTAW15: return  @"W15"; break;
        case UCWMTAW19: return  @"W19"; break;
        case UCWMTAW2: return  @"W2"; break;
        case UCWMTAW3: return  @"W3"; break;
        case UCWMTAW4: return  @"W4"; break;
        case UCWMTAW45: return  @"W45"; break;
        case UCWMTAW47: return  @"W47"; break;
        case UCWMTAW5: return  @"W5"; break;
        case UCWMTAW6: return  @"W6"; break;
        case UCWMTAW8: return  @"W8"; break;
        case UCWMTAW9: return  @"W9"; break;
        case UCWMTAX1: return  @"X1"; break;
        case UCWMTAX2: return  @"X2"; break;
        case UCWMTAX3: return  @"X3"; break;
        case UCWMTAX8: return  @"X8"; break;
        case UCWMTAX9: return  @"X9"; break;
        case UCWMTAY2: return  @"Y2"; break;
        case UCWMTAY7: return  @"Y7"; break;
        case UCWMTAY8: return  @"Y8"; break;
        case UCWMTAZ11: return  @"Z11"; break;
        case UCWMTAZ13: return  @"Z13"; break;
        case UCWMTAZ2: return  @"Z2"; break;
        case UCWMTAZ29: return  @"Z29"; break;
        case UCWMTAZ6: return  @"Z6"; break;
        case UCWMTAZ8: return  @"Z8"; break;
        case UCWMTAZ9: return  @"Z9"; break;
        default: return nil; break;
    }
}

@end
